spring:
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  config:
    import:
      - prod/mongodb.yml
      - prod/email.yml
      - prod/jwt.yml
      - prod/oauth2.yml
      - global/swagger.yml
  web:
    rest-controller:
      prefix: /v1

server:
  servlet:
    context-path: /v1