spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://auth.route-master.org/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-name: kakao
            client-id: ${KAKAO_REST_API_KEY}
            client-authentication-method: POST
            redirect-uri: http://auth.route-master.org/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - age_range
              - birthday
              - friends
              - story_permalink
              - story_read
              - story_publish
              - talk_message
              - talk_calendar

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://127.0.0.1:8000/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8000/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true